### ISSUE TITLE
[Backend] Add functionality to track the completion of a course/activity 

### ISSUE THREAD

**Issue by SaiTarun314** [anshganatra/FitnessApp#6]
As a User, I want to be able to complete the activity/course I have enrolled under apart from the unenrollment option.

**Comment by SaiTarun314** [comment]
Added feature to complete a course/activity which I have enrolled under
<img width="580" alt="image" src="https://github.com/user-attachments/assets/e1b35655-70c4-4306-bb50-cd8b1a4284ab">
<img width="404" alt="image" src="https://github.com/user-attachments/assets/544f01a9-af06-4e20-8c21-156a27037952">

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified application.py to add a new route for completing activities and updated new_dashboard.html to display enrolled activities with a completion button.

You can review changes in this commit: https://github.com/lkilu6456546/anshganatra-FitnessApp-6/commit/f141d8798961034fc35f8e57e310850c3e450e34.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
